from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QFormLayout, QComboBox, QLineEdit, QPushButton, QCheckBox, QGridLayout, QTextEdit
from ui.widgets.card import LMCard

class ProcessingPage(QWidget):
    def __init__(self, window):
        super().__init__()
        root = QVBoxLayout(self)
        root.setContentsMargins(32, 28, 32, 28)
        root.setSpacing(22)
        title = QLabel('Verarbeitung')
        title.setObjectName('pageTitle')
        root.addWidget(title)
        grid = QGridLayout()
        grid.setSpacing(18)

        import_card = LMCard('Import & Workspace')
        form = QFormLayout()
        form.setSpacing(12)
        window.input_mode_combo = QComboBox()
        window.input_mode_combo.addItem('PDF-Ordner mit fertigen Dateien', 'folder')
        window.input_mode_combo.addItem('Eine Gesamt-PDF zum Aufteilen', 'single_pdf')
        saved_input_mode = str(window.settings.get('ui', {}).get('last_pdf_input_mode', 'folder') or 'folder')
        idx = window.input_mode_combo.findData(saved_input_mode)
        if idx >= 0:
            window.input_mode_combo.setCurrentIndex(idx)
        window.pdf_input_edit = QLineEdit(window.settings.get('ui', {}).get('last_pdf_dir', ''))
        window.btn_pdf_select = QPushButton('Ordner wählen')
        pdf_row = QHBoxLayout(); pdf_row.addWidget(window.pdf_input_edit); pdf_row.addWidget(window.btn_pdf_select)
        initial_excel_file = window._current_company_email_excel_file(window.settings.get('selected_company_id'))
        window.excel_file_edit = QLineEdit(initial_excel_file)
        btn_excel = QPushButton('Datei wählen')
        excel_row = QHBoxLayout(); excel_row.addWidget(window.excel_file_edit); excel_row.addWidget(btn_excel)
        window.company_combo = QComboBox(); window.active_company_label = QLabel()
        form.addRow('Eingabemodus', window.input_mode_combo)
        form.addRow('PDF-Quelle', pdf_row)
        form.addRow('Excel-Datei', excel_row)
        form.addRow('Unternehmen', window.company_combo)
        form.addRow('Aktiv', window.active_company_label)
        window.dry_run_checkbox = QCheckBox('Dry-Run: PDF erstellen, aber keine E-Mails senden')
        window.dry_run_checkbox.setChecked(bool(window.settings.get('ui', {}).get('dry_run_default', True)))
        form.addRow('', window.dry_run_checkbox)
        import_card.layout.addLayout(form)
        grid.addWidget(import_card, 0, 0, 2, 2)

        actions = LMCard('Workflow Actions')
        window.btn_check = QPushButton('Adressen prüfen')
        window.btn_check.setObjectName('primary')
        window.btn_send = QPushButton('E-Mails senden')
        window.btn_send_selected = QPushButton('Nur ausgewählte senden')
        actions.layout.addWidget(window.btn_check)
        actions.layout.addWidget(window.btn_send)
        actions.layout.addWidget(window.btn_send_selected)
        hint = QLabel('Empfohlen: zuerst prüfen, dann Versandvorschau bestätigen.')
        hint.setObjectName('muted')
        actions.layout.addWidget(hint)
        grid.addWidget(actions, 0, 2)

        log_card = LMCard('Live Operation Log')
        window.log = QTextEdit(); window.log.setReadOnly(True); window.log.setMinimumHeight(220)
        log_card.layout.addWidget(window.log)
        grid.addWidget(log_card, 1, 2)
        root.addLayout(grid)
        root.addStretch(1)

        window.btn_pdf_select.clicked.connect(window.choose_pdf_input)
        btn_excel.clicked.connect(window.choose_excel_file)
